version: '3'
services:
  back:
    container_name: api_usican
    image: usican/api_usican:1
    command: bash /api_usican/scripts/run_api.sh
    ports:
      - 8000:8000
  front:
    container_name: front_usican
    image: usican/front_usican:1
    ports:
      - 8080:80
