version: '3'
volumes:
  dados:
services:
  back:
    container_name: api_usican
    image: usican/api_usican:1
    command: bash /api_usican/scripts/run.sh
    ports:
      - 8000:8000
    volumes:
      - ./back/scripts:/api_usican/scripts
    depends_on:
      - db
  front:
    container_name: front_usican
    image: usican/front_usican:1
    ports:
      - 8080:80
    depends_on:
      - back
  db:
    container_name: db_usican
    image: postgres:14.2
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=sa_usican
      - POSTGRES_PASSWORD=7X.+TXfvgz@K_
      - POSTGRES_DB=usican
    volumes:
      - dados:/var/lib/postgresql/data
